import React from "react";
import NavBar from "./NavBar";
import {
  VStack,
  Box,
  Text,
  Heading,
  Image,
  StackDivider,
} from "@chakra-ui/react";


const Home = () => {
  return (
    <div>
      <NavBar />

      <VStack
        spacing={8}
        align="stretch"
        divider={<StackDivider borderColor="gray.200" />}
        px={{ base: 4, md: 10, lg: 20 }} // responsive padding
        py={6}
      >
        {/* Hero Image */}
        <Box>
          <Image
            src="/Background.jpg"
            alt="Carbon Footprint"
            borderRadius="lg"
            objectFit="cover"
            w="100%"
            h={{ base: "200px", md: "400px" }}
          />
        </Box>

        {/* Carbon Footprint heading */}
        <Box>
          <Heading color="green.600" size="2xl" textAlign="left">
            CARBON FOOTPRINT
          </Heading>
        </Box>

        {/* What is carbon footprint */}
        <Box>
          <Heading size="lg" mb={3}>
            What is carbon footprint?
          </Heading>
          <Text mb={2}>
            A carbon footprint is the total amount of greenhouse gases (including
            carbon dioxide and methane) that are generated by our actions.
          </Text>
          <Text mb={2}>
            The average carbon footprint for a person in the United States is 16
            tons, one of the highest rates in the world. Globally, the average
            carbon footprint is closer to 4 tons. To have the best chance of
            avoiding a 2℃ rise in global temperatures, the average global carbon
            footprint per year needs to drop to under 2 tons by 2050.
          </Text>
          <Text>
            Lowering individual carbon footprints from 16 tons to 2 tons doesn’t
            happen overnight! By making small changes to our actions, like eating
            less meat, taking fewer connecting flights and line drying our clothes,
            we can start making a big difference.
          </Text>
        </Box>

        {/* How to calculate */}
        <Box>
          <Heading size="lg" mb={3}>
            How to calculate it?
          </Heading>
          <Text>
            Carbon Footprint = (electricity used * 0.0023) + (diesel used * 0.0063) +
            (petrol used * 0.0072) + (water used * 0.001 * 0.149) + (gas used *
            0.18316) + (paper used * 1.04)
          </Text>
        </Box>
      </VStack>
    </div>
  );
};

export default Home;
